<?php

/**
 * @file
 * Contains exo_git_events.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function exo_git_events_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the exo_git_events module.
    case 'help.page.exo_git_events':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('presentation of events') . '</p>';
      return $output;

    default:
  }
}
